// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJp_wNBaCCiJomWBTRbnFaEEuAU7Q3vdI',
    appId: '1:30939584117:web:0fe2e524ed2666dab18a3c',
    messagingSenderId: '30939584117',
    projectId: 'contend-7fa3c',
    authDomain: 'contend-7fa3c.firebaseapp.com',
    storageBucket: 'contend-7fa3c.appspot.com',
    measurementId: 'G-1PSMVHKTYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpuHzojt19g1Dzr5QscvvEpcDQoo9yPKw',
    appId: '1:30939584117:android:1e22621bcc1905bcb18a3c',
    messagingSenderId: '30939584117',
    projectId: 'contend-7fa3c',
    storageBucket: 'contend-7fa3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8IK2JyA3d_tdxZkU--IE_BpKYDDfaE8Y',
    appId: '1:30939584117:ios:f4fdd6c79264911db18a3c',
    messagingSenderId: '30939584117',
    projectId: 'contend-7fa3c',
    storageBucket: 'contend-7fa3c.appspot.com',
    iosBundleId: 'com.example.contend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8IK2JyA3d_tdxZkU--IE_BpKYDDfaE8Y',
    appId: '1:30939584117:ios:5973cb3c87d8e083b18a3c',
    messagingSenderId: '30939584117',
    projectId: 'contend-7fa3c',
    storageBucket: 'contend-7fa3c.appspot.com',
    iosBundleId: 'com.example.contend.RunnerTests',
  );
}
